package com.baishan.nearshop.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.baishan.nearshop.model.ChatUser;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHAT_USER".
*/
public class ChatUserDao extends AbstractDao<ChatUser, Long> {

    public static final String TABLENAME = "CHAT_USER";

    /**
     * Properties of entity ChatUser.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UserID = new Property(0, long.class, "userID", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Portrait = new Property(2, String.class, "portrait", false, "PORTRAIT");
    }


    public ChatUserDao(DaoConfig config) {
        super(config);
    }
    
    public ChatUserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHAT_USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: userID
                "\"NAME\" TEXT," + // 1: name
                "\"PORTRAIT\" TEXT);"); // 2: portrait
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHAT_USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChatUser entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getUserID());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String portrait = entity.getPortrait();
        if (portrait != null) {
            stmt.bindString(3, portrait);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChatUser entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getUserID());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String portrait = entity.getPortrait();
        if (portrait != null) {
            stmt.bindString(3, portrait);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public ChatUser readEntity(Cursor cursor, int offset) {
        ChatUser entity = new ChatUser( //
            cursor.getLong(offset + 0), // userID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // portrait
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChatUser entity, int offset) {
        entity.setUserID(cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPortrait(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ChatUser entity, long rowId) {
        entity.setUserID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ChatUser entity) {
        if(entity != null) {
            return entity.getUserID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ChatUser entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
