package com.baishan.nearshop.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.baishan.nearshop.model.ChatUser;
import com.baishan.nearshop.model.PushParser;
import com.baishan.nearshop.model.PushValue;
import com.baishan.nearshop.model.SearchHistory;

import com.baishan.nearshop.dao.ChatUserDao;
import com.baishan.nearshop.dao.PushParserDao;
import com.baishan.nearshop.dao.PushValueDao;
import com.baishan.nearshop.dao.SearchHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatUserDaoConfig;
    private final DaoConfig pushParserDaoConfig;
    private final DaoConfig pushValueDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;

    private final ChatUserDao chatUserDao;
    private final PushParserDao pushParserDao;
    private final PushValueDao pushValueDao;
    private final SearchHistoryDao searchHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatUserDaoConfig = daoConfigMap.get(ChatUserDao.class).clone();
        chatUserDaoConfig.initIdentityScope(type);

        pushParserDaoConfig = daoConfigMap.get(PushParserDao.class).clone();
        pushParserDaoConfig.initIdentityScope(type);

        pushValueDaoConfig = daoConfigMap.get(PushValueDao.class).clone();
        pushValueDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        chatUserDao = new ChatUserDao(chatUserDaoConfig, this);
        pushParserDao = new PushParserDao(pushParserDaoConfig, this);
        pushValueDao = new PushValueDao(pushValueDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);

        registerDao(ChatUser.class, chatUserDao);
        registerDao(PushParser.class, pushParserDao);
        registerDao(PushValue.class, pushValueDao);
        registerDao(SearchHistory.class, searchHistoryDao);
    }
    
    public void clear() {
        chatUserDaoConfig.clearIdentityScope();
        pushParserDaoConfig.clearIdentityScope();
        pushValueDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
    }

    public ChatUserDao getChatUserDao() {
        return chatUserDao;
    }

    public PushParserDao getPushParserDao() {
        return pushParserDao;
    }

    public PushValueDao getPushValueDao() {
        return pushValueDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

}
